### ISSUE TITLE
[RFC] Benchmark Performance Log Format

### ISSUE THREAD

**Issue by anwang2009** [apache/incubator-tvm#4304]
# Workload record storage proposal

This is a migration and summation of the discussion https://discuss.tvm.ai/t/rfc-benchmark-performance-log-format/4610/15. Please head over there to put in your two cents. This is a WIP issue maintained for visibility. 

We propose a json-based data storage format that unifies how TVM results are tracked. For now the only metric we suggest tracking is execution time, with a focus on reproducibility. We foresees the need for a standard record format to pinpoint the most crucial target areas for future development in TVM. 

## Use cases and motivation

- Easier cross-reference to other frameworks/runs
- Experiment reproduction
- Building nightly perf regression
- Standardization will separate logging and visualization efforts

## Key points to consider

- Maintain reproducibility of experiments based solely on an output record
- Granularity of metrics -- e.g. per-layer vs end-to-end
- config/misc json objects -- enforce prescriptive keys or keep it flexible for now?
- Extensibility of this schema towards desired features in the future

## Proposed format

|header|examples|category|notes/justification|
|---|---|---|---|
|timestamp|1572282699.6|metadata|indicates when this record is logged|
|schema_version|0.1|metadata|ensure reproducibility as we iterate on this schema|
|metadata|{ "docker_tag":"gcr.io/.../0a680", ... }|metadata|`docker_tag` is optional|
|workload|resnet-18|workload|name of workload
|workload_args|{“input_name”: "Input3", “input_shape”: [list_of_shape], “data_layout”: NHCW}|workload|
|workload_metadata|{"class": "vision",<br>"doc_url": "https://github.com/.../README.md",<br>"opset": 7,<br>"type": "body_analysis",<br>"url": "https://onnxzoo...ferplus.tar.gz"<br>"md5": "07fc7..."}|workload|source of workload|
|engine|tvm / onnx-runtime|compiler|
|engine_version|"1.0.0"|compiler|version in semvar format
|engine_config|{“llvm”: “llvm-8”, “nvcc”: 10.1, "accelerator": "MLAS"}|compiler|fields are optionally specified|
|compilation_config|{"opt_level": 3, "layer_schedules": [...]}|compiler|optional|
|software_config|{"os": "ubuntu:18.04",<br>"pip": {<br> "docker": "4.1.0",<br> "gitpython": "3.0.4",<br> "numpy": "1.17.4",<br> "onnx": "1.6.0"},<br> “cudnn”: “cudnn-8”,<br> "cuda_driver”: “480.10.1”}|backend|env dependency list|
|runtime_config|{"num_cpu_threads": 3, ...}|runtime|info on non-hardware, non-software metadata|
|hardware|"gcp-c2-standard-16"|hardware|hardware target summary|
|hardware_config|{"cpu_count": 16,<br>"cloud_machine_type":"c2-standard-16"<br>"memory_GB":64}|hardware|more detailed descriptor of target hardware environment|
|execution_config|{“number”: 1, “repeat”: 10, “min_repeat_ms”, 0}|statistics|workload execution parameters|
|metrics|{"accuracy": 34.1, "compilation_time_ms":24}|statistics|other metrics|
|runtime_raw|[{"runtime_ms": 12, ...}, {"runtime_ms":13,...},...]|statistics|optional raw metrics array|
|runtime_ms_mean|12|statistics|
|runtime_ms_std|3|statistics|

**Comment by tqchen** [comment]
Please share your thoughts about the RFC. this RFC will open for a week, if there are no further comments, we will harden it by bringing it as a part of tvm official document.

**Comment by anwang2009** [comment]
I just updated the initial comment with modifications -- this is the solidification of schema version 0.1.

**Comment by tqchen** [comment]
Awesome, let us bring it to the official document by sending a pr to docs/dev/benchmark.rst

**Comment by tmoreau89** [comment]
@anwang2009 I'd like to suggest one last modification: the removal of the `runtime_config` since many of the fields overlap with the `software_config`.

**Comment by tmoreau89** [comment]
And if possible the addition of an `md5` field under `workload_metadata` to attest the integrity of the model.

**Comment by tmoreau89** [comment]
Other than that looks great 👍

**Comment by anwang2009** [comment]
markdown has been updated to reflect removal of `runtime_config`. 

`num_cpu_threads` can be optionally specified in `hardware_config`, which is optionally json. Optional placement of `cudnn` and `cuda_driver` has been moved to `software_config`. 

`md5` has been added to `workload_metadata`

These changes will be reflected in the tvm PR.

**Comment by tqchen** [comment]
Some further comments wrt to the recently hardware_config change

- I still think it is important to keep the ```runtime_config```, which includes fields like ```num_cpu_threads```. Now that software config mainly specifies the environment dependencies, maybe it makes sense to move num_cpu_threads into runtime_config, as it is something that can be specified through runtime env variable.
- It is important to keep ```hardware_config``` simple, because this is the key that we use to compare among targets.
- docker_tag should not be a required field, as not all experiments have to ran through a docker container. I would even consider move docker_tag as an optional field of engine_config, as it is something related to the software engine.

**Comment by tmoreau89** [comment]
@tqchen `docker_tag` is under metadata; therefore it's mostly seen as optional (and is here for example purposes)
Indeed `num_cpu_threads` is a tricky one and I thought long and hard about this; it makes sense not to place it under `software_config`, and instead could be considered a `hardware` metric. But generally thinking, when do we want to reduce the number of CPU threads that are made usable by the hardware target? For instance with `n1-standard-16` we have 16CPUs. In what situations do we want to reduce the number of available virtual threads? And how would that be enforced? There are multiple ways to do so; one example is while doing `docker run` we can pass the number of CPUs the container can utilize.

**Comment by tqchen** [comment]
I think docker_tag under metadata as long as it is optional (the RFC said the field was required which confuses me).

There are certainly cases when people want to limit the number of threads, e.g. use only the little cores on the phone to save power. While these could have been a nested field in the hardware_config, it makes the field quite complicated.

One of the key property of we should push for the log format is its simplicity. The three fields(engine, workload, hardware_config) are three fields that the user will mostly visit. e.g. ask how can "tvm" do for "resnet-18" on "rasp3b"

Of course the information was incomplete, but the in many cases the three fields already gives a quite complete picture, assuming the default implied target and maximum usage of the resources.

Given that number of threads and other runtime configurations(thread pool setups) are indeed runtime properties that was different from software_config. I think we should keep  the original runtime_config field for these information.

**Comment by tmoreau89** [comment]
That's a sound argument; we should keep runtime config for the `num_cpu_threads` then to store information on non-hardware, and non-software metadata

**Comment by u99127** [comment]
> 
> 
> I think docker_tag under metadata as long as it is optional (the RFC said the field was required which confuses me).
> 
> There are certainly cases when people want to limit the number of threads, e.g. use only the little cores on the phone to save power. While these could have been a nested field in the hardware_config, it makes the field quite complicated.



> 
> One of the key property of we should push for the log format is its simplicity. The three fields(engine, workload, hardware_config) are three fields that the user will mostly visit. e.g. ask how can "tvm" do for "resnet-18" on "rasp3b"

Specifically Rasp3b is fine because it's not big Little . It only has Cortex-A53 cores. 

If the run of the benchmarking is able to pin tasks on specific cores for b.L systems, then I don't see how you can avoid that - unless the TVM stack can only run on the big or only on the little. 

> 
> Of course the information was incomplete, but the in many cases the three fields already gives a quite complete picture, assuming the default implied target and maximum usage of the resources.
> 


Sorry, that  puzzles me again - missing hardware configuration will cause confusion, it certainly  misses some information. 

Not capturing that information would result in user confusion and comparison of apples and oranges. I appreciate the push towards simplicity but it feels that it's at the cost of accuracy. If I were looking at it and I wanted to know the difference then I would prefer to look at it. It's quite likely that if we were looking for performance monitoring over time, then figuring out a way of distinguishing between pinning tasks on big vs pinning tasks on little vs using EAS across the board and therefore note pinning would need to be capture.

> Given that number of threads and other runtime configurations(thread pool setups) are indeed runtime properties that was different from software_config. I think we should keep the original runtime_config field for these information.

**Comment by tqchen** [comment]
To clarify, by in-complete i mean the three fields(model, engine, and hardware) are incomplete. The additional information(engine_config, version, runtime_config) are meant to fill in that gap and provide a complete information.

**Comment by u99127** [comment]
Cool, thanks @tqchen

**Comment by u99127** [comment]
To pick up on a couple of topics from the Pull Request. 

1. I've found that keeping the raw data allows one to process it in other ways in terms of { iteration: 1 runtime: .... } instead of only storing the statistics ?

Different folks would want to do different statistics with the data and we may not be able to specify all the statistics needed on day 1 and would need to keep adding. By keeping raw data we are able to do the aggregation on a later date across history.

2. This is a bit minor - but why are we refering to the tvm stack as "engine" rather than just tvm ? Can we rename engine to tvm , engine_version to tvm_version, engine_configuration to tvm_build_configuration or some such ?

Ramana

**Comment by tqchen** [comment]
After looking at the schema for a bit. I feel that it would be helpful to categorize things into two categories:

-  timestamp, schema, workload, engine, hardware, runtime_ms_mean, runtime_ms_std (I think the runtime_mean_ms and std are important enough for most cases that should be bought into the top-level)
- additional config info and statistics that are meant to supplement the setups.

**Comment by tqchen** [comment]
re @u99127 's comment about raw statistics, given that some executions have to be run over multiple iterations to get a meaningful measurement, individual run stats may not be as meaningful and accurate. We can still provide a runtime_raw array which might be useful for future statistics calculation, but I do think providing mean and std would be what most folks will look for.

the term "engine". the schema was also meant to store baseline benchmarks(e.g. TFLite) and allow cross comparisons between tvm results and baselines, that is why we adopt the term engine.

**Comment by u99127** [comment]
Thanks @tqchen , Ok, now the term "engine" makes sense.

My experience has been different. Some prefer median over mean, others min / max and some other a geometric mean. 

regards
Ramana

**Comment by tmoreau89** [comment]
@u99127 do you lean more towards storing the list of measurements (e.g. over 10 runs) and letting the user implement their aggregation function? Or list multiple ones? Or just agree to standardize towards one (e.g. mean).

**Comment by u99127** [comment]
@tmoreau89  -  I lean more towards storing the list of raw measurements.

**Comment by tqchen** [comment]
To address @u99127 's concern, we could add an optional runtime_raw field. Note we may not necessarily be able to get accurate measurement of exact runs, as cases like GPU executions needs async execution and average over multiple runs, so the statistics will be wrt to the number runs instead of an iteration, see https://docs.tvm.ai/api/python/module.html?highlight=time_evaluator#tvm.module.Module.time_evaluator

**Comment by anwang2009** [comment]
Thanks for everyone's comments! I have made the following amendments in the original post and the pr: 
- `runtime_raw` is an optional top-level field
- `runtime_ms_mean` and `runtime_ms_std` are back at the top level
- `metrics` is a top-level json object that can contain fields like `accuracy` or `compilation_time`
- `runtime_config` is a top-level field again

**Comment by tqchen** [comment]
Thanks everyone for great discussion so far, if there is no further comments, we will merge the current proposal by the end of the week

**Comment by tqchen** [comment]
Thanks for everyone's participation. the first version of the benchmark logging format is now merged.
