### ISSUE TITLE
Building TVM from source for Windows with LLVM support

### ISSUE THREAD

**Issue by burlachenkok** [apache/incubator-tvm#4676]
During building TVM with LLVM support I have faced with two ways how to build TVM for Windows with LLVM support:

(1) cmake -G "Visual Studio 15 2017 Win64" -DUSE_LLVM=ON -DCMAKE_MODULE_PATH="C:/path_to_lvm_sources/llvm-9.0.0.src/llvm-build/lib/cmake/llvm"  ./../

(2) make llvm-config.exe path available in PATH environment variable and then call
cmake -G "Visual Studio 15 2017 Win64" -DUSE_LLVM=ON  ./../

Both ways work for me, but for some reason changing USE_LLVM in cmake/config.cmake does not work for me.

One more thing is that pre-build binaries of LLVM do not include "llvm-config.exe" so for experiments I build LLVM from sources.

I think this information can be useful to upgrade https://docs.tvm.ai/install/from_source.html#building-on-windows

**Comment by tqchen** [comment]
A PR is more than welcomed

**Comment by vexilligera** [comment]
Hi, I am building MXNet with TVM on Windows to support TVMOps. Building LLVM from source with Visual Studio 2017 or later would result in errors due to different constexpr standards, so I have built LLVM and TVM with Clang-CL + Ninja + MSVC LINK/RC, (which means you need to install LLVM binary first). However I'm still having some post build issues when generating tvmop.dll, e.g., unresolved external symbol __gnu_h2f_ieee referenced in function vaddfloat16_5float16_5float16_5

**Comment by Coderx7** [comment]
I recently successfully built LLVM on windows. I documented everything https://discuss.tvm.ai/t/tvm-wont-compile-using-llvm-on-windows/5572 
The last post contains the final solution. hope that helps   
cheers

**Comment by tqchen** [comment]
close as the oroginal instruction seems to be OK.
