### ISSUE TITLE
[RELAY]  kExternalSymbol -> kGlobalSymbol

### ISSUE THREAD

**Issue by tqchen** [apache/incubator-tvm#5210]
As part of the unified IR effort, we introduced the kGlobalSymbol attribute to indicated the linker global symbol of PrimFunc https://github.com/apache/incubator-tvm/blob/master/include/tvm/ir/function.h#L235

This name is largely overlaps with the kExternalSymbol in the current relay custom compiler pass. It would be great to see if we can consolidate the two concepts by simply use kGlobalSymbol

**Comment by tqchen** [comment]
cc @zhiics @comaniac @mbaret

**Comment by comaniac** [comment]
Seems doable. `kExternalSymbol` is added by graph partition pass, so as long as we can make sure the build flow after graph partition pass won't mess up with `kExternalSymbol` and `kGlobalSymbol`, we should be good.

I checked the flow after graph partition pass and mainly located to `compiler engine` and `customized codegen`.

1. Since `compile_engine::LowerExternalFunctions` will first check if `kCompiler` is defined before retriving `kExternalSymbol`, this part should be safe.

2. `customzed codegen` will only receive extenral functions, so it should not matter which symbol we use.

@zhiics please double confirm if I missed anything.

**Comment by zhiics** [comment]
I think we can just replace it as we really only use for runtime lookup. @comaniac you have time to give it a try?

**Comment by tqchen** [comment]
Please do note the type change(from StringImm to runtime::String)

**Comment by zhiics** [comment]
@tqchen runtime::String hasn't yet been exposed to Python side, right?

**Comment by tqchen** [comment]
Not yet, but we have directly use it on the c++ side, this is a TODO in #5047 . If we need a quick python function, we can expose a quick constructor function for now

**Comment by zhiics** [comment]
@tqchen sounds good. I can send a quick change on this.
