### ISSUE TITLE
Can't build large number of operations

### ISSUE THREAD

**Issue by KnowingNothing** [apache/incubator-tvm#5798]
This is an extreme case in which tvm will give Segmentation Fault. 
```py
import tvm


def test1(repeat=10):
  A = tvm.te.placeholder([4, 4])
  Output = tvm.te.compute([4, 4], lambda i, j: A[i, j] + 1)
  for i in range(repeat):
    Output = tvm.te.compute([4, 4], lambda i, j: Output[i, j] + 1)

  sch = tvm.te.create_schedule(Output.op)
  func = tvm.build(sch, [A, Output], target="llvm")


if __name__ == "__main__":
  test1(680)
```
But for some reason, I want tvm to be able to handle such a case, is there any fix to make it?

**Comment by tqchen** [comment]
This is due to the fact of us storinhg the tensor expression recursively. There is an ongoing effort to move more of the parts into TIR, where the sequential structure won't be stored recursively. The problem could be addressed by the migration of more compute infra to TIR, however that will take a few months effort to land. Feel free to open a new discussion thread on https://discuss.tvm.ai/

**Comment by junrushao1994** [comment]
@KnowingNothing you can work around it by “ulimit -s SOME-LARGE-NUMBER” to make stack size larger

**Comment by KnowingNothing** [comment]
I see. Thanks for your response.
