### ISSUE TITLE
[Torch] Support aten::tensor, aten::empty and aten::numel

### ISSUE THREAD

**Issue by zhiqwang** [apache/incubator-tvm#6535]
Hi TVM teams,

TVM currently support pytorch 1.4 and torchvision 0.5. I want to know is there any plan to support pytorch 1.6 version to trace the object detection models in pytorch 1.6?

> For faster rcnn, which is **not** partly scripted and thus can be traced completely, I get following missing ops with PyTorch 1.6
```
NotImplementedError: The following operators are not implemented: ['aten::tensor', 'aten::empty', 'aten::numel']

```

_Originally posted by @masahi in https://github.com/apache/incubator-tvm/pull/6449#issuecomment-693096782_

**Comment by masahi** [comment]
Yes, we want to support a newer version but our quantization support is completely broken in PyTorch 1.6 due to the breaking change they introduced https://github.com/pytorch/pytorch/issues/42497. I don't know a simple workaround for this. 

Either we wait for Torch people to fix this issue or we spend significant effort to add workaround. Until then we are stuck with 1.4 or 1.5 (CI is at 1.4)  

The ops `aten::tensor`, `aten::empty`, and `aten::numel` are very trivial ops actually, so if you want to just convert 1.6 detection models, adding support for them is shouldn't be hard.

**Comment by masahi** [comment]
We'll track 1.6 support at https://github.com/apache/incubator-tvm/issues/6535

**Comment by zhiqwang** [comment]
Hi, That's great news! Relink it to #6594 ?

**Comment by masahi** [comment]
ah sorry, the link is fixed
