### ISSUE TITLE
The following operators are not implemented: ['aten::max_unpool2d'] in pytorch frontend

### ISSUE THREAD

**Issue by IversonTang** [apache/incubator-tvm#6761]
Hello:
I encountered a problem the following operators are not implemented: ['**aten::max_unpool2d**'] when deploying **segnet** model using pytorch frontend. Then I observed the operator **aten:: max_ pool2d_ with_ indicies** seems return dummy indices in **relay/frontend/pytorch.py**.How can I modify operator max_ pool2d_ with_ indicies to save indicies and add new operator max_unpool2d?

**Comment by masahi** [comment]
Unfortunately, upsampling via unpooling is not possible with TVM, since TVM max pool op doesn't record indices (that's why we return dummy indices from `max_ pool2d_ with_ indicies`). If possible, you can modify your model to do upsampling via `torch.interpolate(...)` function. 

For further questions, please use the forum instead.
