### ISSUE TITLE
window build restrictions

### ISSUE THREAD

**Issue by mei-ye** [apache/incubator-tvm#6806]
On windows, you can’t mix debug and release DLLs.  As a result, LLVM and TVM must have the same debug or release build. 
For the vulkan target, the downloaded VulkanSDK is a release build, which leads to link-time errors for the debug build of TVM.
For the llvm target, debug build runs into two problems:
1.	LLVM_ENABLE_ABI_BREAKING_CHECKS in LLVM is set to 1 which is incompatible with TVM.
2.	Many symbols are not exported .  As a workaround, we can use: -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True.  However,  debug build apparently has many more symbols to export which exceeds Windows' restriction:  number of exported symbols to be no more than 65536.

**Comment by tqchen** [comment]
Thanks @mei-ye , the topic of windows build is better suited in https://discuss.tvm.apache.org/. Yes I think it is important to make use of the relase build instead of debug build in windows as most of the packages are release.  We do expose the symbols that are under TVM_DLL, which covers most of the usages in the include, but would not export other symbols.
